parameters:
#    todpole.example.class: Todpole\TodpoleBundle\Example

services:
#    todpole.example:
#        class: %todpole.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
